"""initial

Revision ID: 0b04110fe742
Revises:
Create Date: 2026-04-20 12:21:02.406806
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0b04110fe742"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_investors_cik"), "investors", ["cik"], unique=True)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("investor_id", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=10), nullable=True),
        sa.Column("filing_type_filter", sa.String(length=20), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sa.String(length=512), nullable=True),
        sa.Column("last_triggered_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["investor_id"],
            ["investors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_investor_id"), "alerts", ["investor_id"], unique=False)
    op.create_index(op.f("ix_alerts_ticker"), "alerts", ["ticker"], unique=False)
    op.create_table(
        "filings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("investor_id", sa.Integer(), nullable=False),
        sa.Column("filing_type", sa.String(length=20), nullable=False),
        sa.Column("accession_number", sa.String(length=25), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("period_of_report", sa.Date(), nullable=True),
        sa.Column("subject_company_name", sa.String(length=255), nullable=True),
        sa.Column("subject_company_ticker", sa.String(length=10), nullable=True),
        sa.Column("subject_company_cusip", sa.String(length=9), nullable=True),
        sa.Column("raw_url", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["investor_id"],
            ["investors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("accession_number"),
    )
    op.create_index(op.f("ix_filings_filing_date"), "filings", ["filing_date"], unique=False)
    op.create_index(op.f("ix_filings_filing_type"), "filings", ["filing_type"], unique=False)
    op.create_index(op.f("ix_filings_investor_id"), "filings", ["investor_id"], unique=False)
    op.create_index(op.f("ix_filings_subject_company_ticker"), "filings", ["subject_company_ticker"], unique=False)
    op.create_table(
        "holdings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filing_id", sa.Integer(), nullable=False),
        sa.Column("issuer_name", sa.String(length=255), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=True),
        sa.Column("cusip", sa.String(length=9), nullable=True),
        sa.Column("shares", sa.BigInteger(), nullable=True),
        sa.Column("market_value_usd", sa.BigInteger(), nullable=True),
        sa.Column("pct_of_class", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("change_type", sa.String(length=20), nullable=True),
        sa.Column("shares_delta", sa.BigInteger(), nullable=True),
        sa.Column("pct_delta", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["filing_id"],
            ["filings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holdings_change_type"), "holdings", ["change_type"], unique=False)
    op.create_index(op.f("ix_holdings_cusip"), "holdings", ["cusip"], unique=False)
    op.create_index(op.f("ix_holdings_filing_id"), "holdings", ["filing_id"], unique=False)
    op.create_index(op.f("ix_holdings_ticker"), "holdings", ["ticker"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_holdings_ticker"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_filing_id"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_cusip"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_change_type"), table_name="holdings")
    op.drop_table("holdings")
    op.drop_index(op.f("ix_filings_subject_company_ticker"), table_name="filings")
    op.drop_index(op.f("ix_filings_investor_id"), table_name="filings")
    op.drop_index(op.f("ix_filings_filing_type"), table_name="filings")
    op.drop_index(op.f("ix_filings_filing_date"), table_name="filings")
    op.drop_table("filings")
    op.drop_index(op.f("ix_alerts_ticker"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_investor_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_investors_cik"), table_name="investors")
    op.drop_table("investors")
    # ### end Alembic commands ###
