"""add_transaction_summary

Revision ID: 12a8e9f6b08f
Revises: 0b04110fe742
Create Date: 2026-04-20 15:44:37.642132
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "12a8e9f6b08f"
down_revision: str | None = "0b04110fe742"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("filings", sa.Column("transaction_summary", sa.String(), nullable=True))
    op.alter_column("filings", "shares_owned", existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=True)
    op.alter_column(
        "filings", "transaction_purpose", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "filings", "transaction_purpose", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column("filings", "shares_owned", existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=True)
    op.drop_column("filings", "transaction_summary")
    # ### end Alembic commands ###
