"""add_research_summary

Revision ID: daa9c35b99fe
Revises: 12a8e9f6b08f
Create Date: 2026-04-20 16:09:56.118355
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "daa9c35b99fe"
down_revision: str | None = "12a8e9f6b08f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("filings", sa.Column("research_summary", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filings", "research_summary")
    # ### end Alembic commands ###
